#
# Copyright (c) 2017-2020 Fernando Pelliccioni
#

branches:
  only:
  - master
  - dev
  - test

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.7"
   services:
     - docker

node_js:
  - "node"
  - "8"

matrix:
   include:

      - <<: *linux
        env: UNIT_TESTS=true UPLOAD_PKG=false
        compiler: gcc
        python: "3.7"


install:

  - set -e
  - set -x

  - |
    pip install wheel --upgrade
    pip install twine --upgrade
    pip install cpuid --upgrade

script:

  - set -e
  - set -x

  - python -c 'import cpuid; _, b, _, _ = cpuid.cpuid_count(7, 0); print((b >> 29) & 1)'
  - python test.py




notifications:
  email: 
    - fpelliccioni@gmail.com
  webhooks:
    urls: https://webhooks.gitter.im/e/a19dd2b03bf676d2b622
    on_success: change
    on_failure: always

